In [1]:
import pandas as pd

#### Data loading
- xlrd 모듈이 없을 경우, conda install xlrd

In [2]:
!conda install --y xlrd

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/min/miniconda3

  added / updated specs:
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.10.26 |       hca03da5_2         116 KB
    certifi-2021.5.30          |   py38hca03da5_1         139 KB
    conda-4.11.0               |   py38hca03da5_0        14.4 MB
    xlrd-2.0.1                 |     pyhd3eb1b0_0          90 KB
    ------------------------------------------------------------
                                           Total:        14.8 MB

The following NEW packages will be INSTALLED:

  xlrd               pkgs/main/noarch::xlrd-2.0.1-pyhd3eb1b0_0

The following packages will be UPDATED:

  ca-certificates                      2021.4.13-hca03da5_1 --> 2021.10.26-hca03da5_2
  certifi                          2020.12.5-py38hca03da5_0 --> 2021.5.30-py38hca03da5_1
  conda                               4.10.1-py38hca03da5_1 --> 4.11.0-py38hca03da5_0



Downloading and Extracting Packages
ca-certificates-2021 | 116 KB    | ##################################### | 100%
conda-4.11.0         | 14.4 MB   | ##################################### | 100%
xlrd-2.0.1           | 90 KB     | ##################################### | 100%
certifi-2021.5.30    | 139 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [5]:
import numpy as np
df = pd.read_csv('data.csv', encoding='cp949')
df.head() #처음 다섯줄 출력

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
0,1,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,4562,서울특별시 중구 을지로 39길 29,02-2260-7114
1,2,중앙/권역,코로나19 중부권역 예방접종센터,순천향대 천안병원,천안시 실내배드민턴장 1층,31212,충청남도 천안시 동남구 천안대로 357,NaN
2,3,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,61452,광주광역시 동구 필문대로 365,062-220-3739
3,4,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,50612,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955

#### data selction with index number and column names

In [7]:
df["센터명"].head(2)

0      코로나19 중앙 예방접종센터
1    코로나19 중부권역 예방접종센터
Name: 센터명, dtype: object

In [8]:
df[["센터명", "운영기관", "시설명"]].head(3)

                 센터명       운영기관             시설명
0    코로나19 중앙 예방접종센터    국립중앙의료원      국립중앙의료원 D동
1  코로나19 중부권역 예방접종센터  순천향대 천안병원  천안시 실내배드민턴장 1층
2  코로나19 호남권역 예방접종센터      조선대병원  조선대학교병원 의성관 5층

In [9]:
df[:10]

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
0,1,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,4562,서울특별시 중구 을지로 39길 29,02-2260-7114
1,2,중앙/권역,코로나19 중부권역 예방접종센터,순천향대 천안병원,천안시 실내배드민턴장 1층,31212,충청남도 천안시 동남구 천안대로 357,NaN
2,3,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,61452,광주광역시 동구 필문대로 365,062-220-3739
3,4,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,50612,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955
5,6,지역,코로나19 서울특별시 성동구 예방접종센터,NaN,성동구청 대강당(3층),4750,서울특별시 성동구 고산자로 270,02-2286-5084
6,7,지역,코로나19 부산광역시 부산진구 예방접종센터,NaN,부산시민공원 시민사랑채,47197,부산 부산진구 시민공원로 73,051-605-8633
7,8,지역,코로나19 인천광역시 연수구 예방접종센터,NaN,선학경기장 선학체육관,21908,인천광역시 연수구 경원대로 526,032-749-8121
8,9,지역,코로나19 광주광역시 서구 예방접종센터,NaN,빛고을체육관,62048,광주광역시 서구 금화로 278,062-371-8731
9,10,지역,코로나19 대전광역시 유성구 예방접종센터,NaN,유성종합스포츠센터,34128,대전광역시 유성구 유성대로 978,042-611-5050

In [10]:
df["센터명"][:3]

0      코로나19 중앙 예방접종센터
1    코로나19 중부권역 예방접종센터
2    코로나19 호남권역 예방접종센터
Name: 센터명, dtype: object

In [12]:
account_serires = df["센터명"]
account_serires[:3]

0      코로나19 중앙 예방접종센터
1    코로나19 중부권역 예방접종센터
2    코로나19 호남권역 예방접종센터
Name: 센터명, dtype: object

In [13]:
account_serires[[1,5,2]]

1         코로나19 중부권역 예방접종센터
5    코로나19 서울특별시 성동구 예방접종센터
2         코로나19 호남권역 예방접종센터
Name: 센터명, dtype: object

In [14]:
account_serires[account_serires<250000]

TypeError: '<' not supported between instances of 'str' and 'int'

In [15]:
df.index = df["account"]

KeyError: 'account'

In [27]:
df.head()

,account,name,street,city,state,postal-code,Jan,Feb,Mar
account,,,,,,,,,
211829,211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
320563,320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
648336,648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
109996,109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
121213,121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

In [28]:
del df["account"]
df.head()

,name,street,city,state,postal-code,Jan,Feb,Mar
account,,,,,,,,
211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
320563,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
121213,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

In [29]:
df[["name","street"]][:2]

                               name              street
account
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [30]:
df.loc[[211829,320563],["name","street"]]

                               name              street
account
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [31]:
df[["name", "street"]].iloc[:10]

,name,street
account,,
211829,"Kerluke, Koepp and Hilpert",34456 Sean Highway
320563,Walter-Trantow,1311 Alvis Tunnel
648336,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231
109996,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144
121213,Bauch-Goldner,7274 Marissa Common
132971,"Williamson, Schumm and Hettinger",89403 Casimer Spring
145068,Casper LLC,340 Consuela Bridge Apt. 400
205217,Kovacek-Johnston,91971 Cronin Vista Suite 601
209744,Champlin-Morar,26739 Grant Lock
212303,Gerhold-Maggio,366 Maggio Grove Apt. 998

### reindex

In [32]:
df.index = list(range(0,15))
df.head()

,name,street,city,state,postal-code,Jan,Feb,Mar
0,"Kerluke, Koepp and Hilpert",34456 Sean Highway,New Jaycob,Texas,28752,10000,62000,35000
1,Walter-Trantow,1311 Alvis Tunnel,Port Khadijah,NorthCarolina,38365,95000,45000,35000
2,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,New Lilianland,Iowa,76517,91000,120000,35000
3,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Hyattburgh,Maine,46021,45000,120000,10000
4,Bauch-Goldner,7274 Marissa Common,Shanahanchester,California,49681,162000,120000,35000

### data drop

In [16]:
df

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
0,1,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,4562,서울특별시 중구 을지로 39길 29,02-2260-7114
1,2,중앙/권역,코로나19 중부권역 예방접종센터,순천향대 천안병원,천안시 실내배드민턴장 1층,31212,충청남도 천안시 동남구 천안대로 357,NaN
2,3,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,61452,광주광역시 동구 필문대로 365,062-220-3739
3,4,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,50612,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955
...,...,...,...,...,...,...,...,...
279,280,지역,코로나19 충청북도 청주시 흥덕구 예방접종센터,NaN,(舊)흥덕구청,28426,충청북도 청주시 흥덕구 대농로 88,043-201-0999
280,281,지역,코로나19 경기도 파주시 예방접종센터,NaN,운정행복센터,10894,경기도 파주시 와석순환로 415,031-940-5597
281,282,지역,코로나19 경기도 남양주시 예방접종센터,NaN,화도체육문화센터,12178,경기도 남양주시 화도읍 수레로 1259,031-590-2598
282,283,지역,코로나19 경기도 시흥시 예방접종센터,NaN,시흥국민체육센터,14976,경기도 시흥시 하중로 226,031-310-6822
283,284,지역,코로나19 충청남도 당진시 예방접종센터,NaN,국민체육센터,31772,충청남도 당진시 시청1로 30,041-360-6138

In [17]:
df.drop(1)

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
0,1,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,4562,서울특별시 중구 을지로 39길 29,02-2260-7114
2,3,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,61452,광주광역시 동구 필문대로 365,062-220-3739
3,4,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,50612,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955
5,6,지역,코로나19 서울특별시 성동구 예방접종센터,NaN,성동구청 대강당(3층),4750,서울특별시 성동구 고산자로 270,02-2286-5084
...,...,...,...,...,...,...,...,...
279,280,지역,코로나19 충청북도 청주시 흥덕구 예방접종센터,NaN,(舊)흥덕구청,28426,충청북도 청주시 흥덕구 대농로 88,043-201-0999
280,281,지역,코로나19 경기도 파주시 예방접종센터,NaN,운정행복센터,10894,경기도 파주시 와석순환로 415,031-940-5597
281,282,지역,코로나19 경기도 남양주시 예방접종센터,NaN,화도체육문화센터,12178,경기도 남양주시 화도읍 수레로 1259,031-590-2598
282,283,지역,코로나19 경기도 시흥시 예방접종센터,NaN,시흥국민체육센터,14976,경기도 시흥시 하중로 226,031-310-6822
283,284,지역,코로나19 충청남도 당진시 예방접종센터,NaN,국민체육센터,31772,충청남도 당진시 시청1로 30,041-360-6138

In [18]:
df

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
0,1,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,4562,서울특별시 중구 을지로 39길 29,02-2260-7114
1,2,중앙/권역,코로나19 중부권역 예방접종센터,순천향대 천안병원,천안시 실내배드민턴장 1층,31212,충청남도 천안시 동남구 천안대로 357,NaN
2,3,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,61452,광주광역시 동구 필문대로 365,062-220-3739
3,4,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,50612,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955
...,...,...,...,...,...,...,...,...
279,280,지역,코로나19 충청북도 청주시 흥덕구 예방접종센터,NaN,(舊)흥덕구청,28426,충청북도 청주시 흥덕구 대농로 88,043-201-0999
280,281,지역,코로나19 경기도 파주시 예방접종센터,NaN,운정행복센터,10894,경기도 파주시 와석순환로 415,031-940-5597
281,282,지역,코로나19 경기도 남양주시 예방접종센터,NaN,화도체육문화센터,12178,경기도 남양주시 화도읍 수레로 1259,031-590-2598
282,283,지역,코로나19 경기도 시흥시 예방접종센터,NaN,시흥국민체육센터,14976,경기도 시흥시 하중로 226,031-310-6822
283,284,지역,코로나19 충청남도 당진시 예방접종센터,NaN,국민체육센터,31772,충청남도 당진시 시청1로 30,041-360-6138

In [19]:
df.drop([0,1,2,3])

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955
5,6,지역,코로나19 서울특별시 성동구 예방접종센터,NaN,성동구청 대강당(3층),4750,서울특별시 성동구 고산자로 270,02-2286-5084
6,7,지역,코로나19 부산광역시 부산진구 예방접종센터,NaN,부산시민공원 시민사랑채,47197,부산 부산진구 시민공원로 73,051-605-8633
7,8,지역,코로나19 인천광역시 연수구 예방접종센터,NaN,선학경기장 선학체육관,21908,인천광역시 연수구 경원대로 526,032-749-8121
8,9,지역,코로나19 광주광역시 서구 예방접종센터,NaN,빛고을체육관,62048,광주광역시 서구 금화로 278,062-371-8731
...,...,...,...,...,...,...,...,...
279,280,지역,코로나19 충청북도 청주시 흥덕구 예방접종센터,NaN,(舊)흥덕구청,28426,충청북도 청주시 흥덕구 대농로 88,043-201-0999
280,281,지역,코로나19 경기도 파주시 예방접종센터,NaN,운정행복센터,10894,경기도 파주시 와석순환로 415,031-940-5597
281,282,지역,코로나19 경기도 남양주시 예방접종센터,NaN,화도체육문화센터,12178,경기도 남양주시 화도읍 수레로 1259,031-590-2598
282,283,지역,코로나19 경기도 시흥시 예방접종센터,NaN,시흥국민체육센터,14976,경기도 시흥시 하중로 226,031-310-6822
283,284,지역,코로나19 충청남도 당진시 예방접종센터,NaN,국민체육센터,31772,충청남도 당진시 시청1로 30,041-360-6138

In [37]:
matrix = df.as_matrix()
matrix[:3]

array([['Kerluke, Koepp and Hilpert', '34456 Sean Highway', 'New Jaycob',
        'Texas', 28752, 10000, 62000, 35000],
       ['Walter-Trantow', '1311 Alvis Tunnel', 'Port Khadijah',
        'NorthCarolina', 38365, 95000, 45000, 35000],
       ['Bashirian, Kunde and Price',
        '62184 Schamberger Underpass Apt. 231', 'New Lilianland', 'Iowa',
        76517, 91000, 120000, 35000]], dtype=object)

In [ ]:
matrix[:,-3:]

In [ ]:
matrix[:,-3:].sum(axis=1)

In [40]:
df.drop("city",axis=1).head()

,name,street,state,postal-code,Jan,Feb,Mar
0,"Kerluke, Koepp and Hilpert",34456 Sean Highway,Texas,28752,10000,62000,35000
1,Walter-Trantow,1311 Alvis Tunnel,NorthCarolina,38365,95000,45000,35000
2,"Bashirian, Kunde and Price",62184 Schamberger Underpass Apt. 231,Iowa,76517,91000,120000,35000
3,"D'Amore, Gleichner and Bode",155 Fadel Crescent Apt. 144,Maine,46021,45000,120000,10000
4,Bauch-Goldner,7274 Marissa Common,California,49681,162000,120000,35000

In [20]:
df

,연번,센터유형,센터명,운영기관,시설명,우편번호,주소,사무실전화번호
0,1,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,4562,서울특별시 중구 을지로 39길 29,02-2260-7114
1,2,중앙/권역,코로나19 중부권역 예방접종센터,순천향대 천안병원,천안시 실내배드민턴장 1층,31212,충청남도 천안시 동남구 천안대로 357,NaN
2,3,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,61452,광주광역시 동구 필문대로 365,062-220-3739
3,4,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,50612,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,5,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,41931,대구시 중구 달성로 56,053-661-3955
...,...,...,...,...,...,...,...,...
279,280,지역,코로나19 충청북도 청주시 흥덕구 예방접종센터,NaN,(舊)흥덕구청,28426,충청북도 청주시 흥덕구 대농로 88,043-201-0999
280,281,지역,코로나19 경기도 파주시 예방접종센터,NaN,운정행복센터,10894,경기도 파주시 와석순환로 415,031-940-5597
281,282,지역,코로나19 경기도 남양주시 예방접종센터,NaN,화도체육문화센터,12178,경기도 남양주시 화도읍 수레로 1259,031-590-2598
282,283,지역,코로나19 경기도 시흥시 예방접종센터,NaN,시흥국민체육센터,14976,경기도 시흥시 하중로 226,031-310-6822
283,284,지역,코로나19 충청남도 당진시 예방접종센터,NaN,국민체육센터,31772,충청남도 당진시 시청1로 30,041-360-6138

In [21]:
df.drop(["연번", "우편번호"],axis=1)

,센터유형,센터명,운영기관,시설명,주소,사무실전화번호
0,중앙/권역,코로나19 중앙 예방접종센터,국립중앙의료원,국립중앙의료원 D동,서울특별시 중구 을지로 39길 29,02-2260-7114
1,중앙/권역,코로나19 중부권역 예방접종센터,순천향대 천안병원,천안시 실내배드민턴장 1층,충청남도 천안시 동남구 천안대로 357,NaN
2,중앙/권역,코로나19 호남권역 예방접종센터,조선대병원,조선대학교병원 의성관 5층,광주광역시 동구 필문대로 365,062-220-3739
3,중앙/권역,코로나19 영남권역 예방접종센터,양산 부산대병원,양산 부산대병원 기숙사동 1층,경상남도 양산시 물금읍 금오로 20,055-360-6701
4,지역,코로나19 대구광역시 중구 예방접종센터,NaN,계명대학교 대구동산병원 별관,대구시 중구 달성로 56,053-661-3955
...,...,...,...,...,...,...
279,지역,코로나19 충청북도 청주시 흥덕구 예방접종센터,NaN,(舊)흥덕구청,충청북도 청주시 흥덕구 대농로 88,043-201-0999
280,지역,코로나19 경기도 파주시 예방접종센터,NaN,운정행복센터,경기도 파주시 와석순환로 415,031-940-5597
281,지역,코로나19 경기도 남양주시 예방접종센터,NaN,화도체육문화센터,경기도 남양주시 화도읍 수레로 1259,031-590-2598
282,지역,코로나19 경기도 시흥시 예방접종센터,NaN,시흥국민체육센터,경기도 시흥시 하중로 226,031-310-6822
283,지역,코로나19 충청남도 당진시 예방접종센터,NaN,국민체육센터,충청남도 당진시 시청1로 30,041-360-6138

In [ ]:
matrix = df.as_matrix()
matrix